baseurl = "https://dongri.github.io/"
languageCode = "en-us"
title = "dongri"
# theme = "crisp"
# theme = "pixyll"
theme = "boro"

[params]
  message = "Hello World"
[permalinks]
  post = "/:year/:month/:title/"
